---
title: "cluster_summaries"
author: "Jonathan Zisk"
date: "2024-05-09"
output: html_document
---

```{r setup_packages, results='hide', warning = FALSE, message = FALSE}
library(tidyverse)
library(tidycensus)
library(sf)
library(gt)
library(gtExtras)
library(factoextra)
library(ggthemes)
library(RColorBrewer)
library(tmap)
library(tigris)
library(webshot2)
```


```{r assigning clusters}

#### Chattanooga 

Chatt_census <- read.csv("Chatt_census12.csv")


#Scaling the data (code from here: https://stackoverflow.com/questions/15215457/standardize-data-columns-in-r)
Chatt_scaled <- Chatt_census %>% 
  mutate(PubSNAP_rate = PubSNAP/TotalPop, 
         RenterOcc_rate = RenterOcc/TotalPop, 
         WhitePop_rate = WhitePop / TotalPop, 
         Grad_deg_rate = Grad_deg/TotalPop, 
         PubTrans_commute_ratio = PubTrans_commute/Drive_commute, 
         Citizen_Ratio = NotUS_cit/US_cit) %>% 
  select(c(GEOID,MedHHInc, MedHomeVal, MedHUBuilt, PubSNAP_rate, RenterOcc_rate,
           WhitePop_rate, Grad_deg_rate, PubTrans_commute_ratio, Citizen_Ratio)) %>% 
  mutate_at(c(2:10), ~(scale(.) %>% 
                         as.vector)) %>% 
  na.omit()
  

#Identifying number of clusters

set.seed(123)

km.out <- kmeans(Chatt_scaled, centers = 20, nstart = 20)
km.out

#### Scree Plot, from MNR / PBN ####

# First, identify the number of clusters (k)
# "Elbow" method
mydata <- Chatt_scaled
wss <- (nrow(mydata)-1)*sum(apply(mydata,2,var))
for (i in 2:15) wss[i] <- sum(kmeans(mydata,
                                     centers=i)$withinss)
plot(1:15, wss, type="b", xlab="Number of Clusters",
     ylab="Within cluster sum of squares",
     main="Assessing the Optimal Number of Clusters",
     pch=20, cex=2)
abline(v=4, lty="dashed", lwd=2, col="red")

### 4 clusters are best
k <- 4
set.seed(123)
# Build model with k clusters: km.out
km.out <- kmeans(Chatt_scaled, centers = k, nstart = 20)

##Assigning Cluster IDs
Chatt_scaled$cluster_id <- factor(km.out$cluster)

ggplot(Chatt_scaled, 
       aes(x= MedHHInc, y= WhitePop_rate, color = cluster_id))+ 
  geom_point()

chatt_join <- Chatt_scaled %>% 
  select(c(GEOID, cluster_id)) 


Chatt_census12 <- 
  get_acs(geography = "tract", 
          variables = c("B25026_001E"),   year=2012, state=47, county=065, 
          geometry=TRUE, output="wide"
          ) %>% 
  mutate(GEOID = as.numeric(GEOID))

Chatt_census_clusters <- Chatt_census12 %>% 
  left_join(chatt_join) 

tm_shape(Chatt_census12)+ 
  tm_polygons()

#### Nashville 

Nash_census <- read.csv("Nash_census12.csv")


#Scaling the data (code from here: https://stackoverflow.com/questions/15215457/standardize-data-columns-in-r)
Nash_scaled <- Nash_census %>% 
  mutate(PubSNAP_rate = PubSNAP/TotalPop, 
         RenterOcc_rate = RenterOcc/TotalPop, 
         WhitePop_rate = WhitePop / TotalPop, 
         Grad_deg_rate = Grad_deg/TotalPop, 
         PubTrans_commute_ratio = PubTrans_commute/Drive_commute, 
         Citizen_Ratio = NotUS_cit/US_cit) %>% 
  select(c(GEOID,MedHHInc, MedHomeVal, MedHUBuilt, PubSNAP_rate, RenterOcc_rate,
           WhitePop_rate, Grad_deg_rate, PubTrans_commute_ratio, Citizen_Ratio)) %>% 
  na.omit() %>% 
  mutate_at(c(2:10), ~(scale(.) %>% 
                         as.vector))


#Identifying number of clusters

set.seed(123)

km.out <- kmeans(Nash_scaled, centers = 20, nstart = 20)
km.out

#### Scree Plot, from MNR / PBN ####

# First, identify the number of clusters (k)
# "Elbow" method
mydata <- Nash_scaled
wss <- (nrow(mydata)-1)*sum(apply(mydata,2,var))
for (i in 2:15) wss[i] <- sum(kmeans(mydata,
                                     centers=i)$withinss)
plot(1:15, wss, type="b", xlab="Number of Clusters",
     ylab="Within cluster sum of squares",
     main="Assessing the Optimal Number of Clusters",
     pch=20, cex=2)
abline(v=4, lty="dashed", lwd=2, col="red")

### 4 clusters are best
k <- 4
set.seed(123)
# Build model with k clusters: km.out
km.out <- kmeans(Nash_scaled, centers = k, nstart = 20)

##Assigning Cluster IDs
Nash_scaled$cluster_id <- factor(km.out$cluster)

ggplot(Nash_scaled, 
       aes(x= MedHHInc, y= WhitePop_rate, color = cluster_id))+ 
  geom_point()

nash_join <- Nash_scaled %>% 
  select(c(GEOID, cluster_id))


Nash_census19 <- 
  get_acs(geography = "tract", 
          variables = c("B25026_001E"), 
          year=2019, state=47, county=037, 
          geometry=TRUE, output="wide") %>% 
  mutate(GEOID = as.numeric(GEOID))

Nash_census_clusters <- Nash_census19 %>% 
  left_join(nash_join) 

tm_shape(Nash_census_clusters)+ 
  tm_polygons(fill = "cluster_id")

```


```{r}

chatt_cluster_summary <- Chatt_census_clusters %>% 
  st_drop_geometry() %>% 
  select(c(GEOID, cluster_id)) %>% 
  right_join(Chatt_census) %>% 
  select(c(cluster_id, MedHHInc, TotalPop, MedRent, WhitePop, BlackPop, HispLatPop, Bach_deg,Grad_deg, PubTrans_commute)) %>% 
  mutate(n_clust = 1) %>%  
  group_by(cluster_id) %>% 
  summarise(across(c(TotalPop,WhitePop, BlackPop, HispLatPop, Bach_deg,Grad_deg, PubTrans_commute, n_clust), sum), 
            med_inc = mean(MedHHInc), 
            med_rent = mean(MedRent)) %>% 
mutate(
white_rate = WhitePop/TotalPop, 
         black_rate = BlackPop/TotalPop, 
         hisp_rate = HispLatPop/TotalPop, 
         deg_rate = (Bach_deg+Grad_deg)/TotalPop, 
         trans_com_rate = PubTrans_commute / TotalPop) %>% 
  select(c(cluster_id, n_clust,med_inc, med_rent, white_rate, black_rate, hisp_rate, deg_rate, trans_com_rate)) %>% 
  na.omit()


chatt_cluster_summary %>% 
  gt() %>% 
  fmt_percent(columns = 5:9, 
              decimals = 1) %>% 
  fmt_currency(columns = 3:4, 
               decimals = 0) %>% 
  cols_label(cluster_id = "Cluster", 
             n_clust = "Count", 
             med_inc = "Median Income",
              med_rent = "Median Rent",
             white_rate = "White", 
             black_rate = "Black", 
             hisp_rate = "Hispanic", 
             deg_rate = "College Degree", 
             trans_com_rate = "Commute by Transit") %>%
  cols_width(3:9 ~ px(200)) %>%
  tab_header(title = "Summary of Cluster Characteristics for Chattanooga",
             subtitle = "Source: 2012 ACS 5-year Estimate") %>% 
  gt_theme_538()

```

```{r}

nash_cluster_summary <- Nash_census_clusters %>% 
  st_drop_geometry() %>% 
  select(c(GEOID, cluster_id)) %>% 
  right_join(Nash_census) %>% 
  select(c(cluster_id, MedHHInc, TotalPop, MedRent, WhitePop, BlackPop, HispLatPop, Bach_deg,Grad_deg, PubTrans_commute)) %>% 
  mutate(n_clust = 1) %>%  
  group_by(cluster_id) %>% 
  summarise(across(c(TotalPop,WhitePop, BlackPop, HispLatPop, Bach_deg,Grad_deg, PubTrans_commute, n_clust), sum), 
            med_inc = mean(MedHHInc), 
            med_rent = mean(MedRent, na.rm=T)) %>% 
mutate(
white_rate = WhitePop/TotalPop, 
         black_rate = BlackPop/TotalPop, 
         hisp_rate = HispLatPop/TotalPop, 
         deg_rate = (Bach_deg+Grad_deg)/TotalPop, 
         trans_com_rate = PubTrans_commute / TotalPop) %>% 
  select(c(cluster_id, n_clust,med_inc, med_rent, white_rate, black_rate, hisp_rate, deg_rate, trans_com_rate)) %>%  
  na.omit()

nash_cluster_summary %>% 
  gt() %>% 
  fmt_percent(columns = 5:9, 
              decimals = 1) %>% 
  fmt_currency(columns = 3:4, 
               decimals = 0) %>% 
  cols_label(cluster_id = "Cluster", 
             n_clust = "Count", 
             med_inc = "Median Income",
              med_rent = "Median Rent",
             white_rate = "White", 
             black_rate = "Black", 
             hisp_rate = "Hispanic", 
             deg_rate = "College Degree", 
             trans_com_rate = "Commute by Transit") %>%
  cols_width(3:9 ~ px(200)) %>%
  tab_header(title = "Summary of Cluster Characteristics for Nashville",
             subtitle = "Source: 2012 ACS 5-year Estimate") %>% 
  gt_theme_538()

```
